# Generated by Django 6.0.6 on 2026-06-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_comment_like_postreactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('pending', 'در انتظار تایید'), ('published', 'منتشر شده'), ('rejected', 'رد شده')], default='pending', max_length=20),
        ),
    ]
