# Generated by Django 6.0.6 on 2026-06-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_post_is_published_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
